### ISSUE TITLE
Tipado de dispositivo

### ISSUE THREAD

**Issue by toni03** [flythings/python#1]
Añadir la posibilidad de incorporar el tipo del dispositivo en la generación de observaciones, en lugar de añadirlo manualmente.

Idem con el nombre y otros campos que se han añadido en FlyThings en los ultimos meses.

**Comment by SunD1995** [comment]
Tanto tipo de dispositivo como nombre de dispositivo se incluyó en la .1.4.6
Habría que incluir el resto que se hayan añadadido para la siguiente.

**Comment by toni03** [comment]
Cierro esta issue, que lo prioritario esta tipo de dispositivo, si hace falta algo mas en el futuro se abre una nueva issue
