### ISSUE TITLE
Pequeñas mejoras

### ISSUE THREAD

**Issue by toni03** [flythings/python#9]
* [ ] Mejorar el README principal
* [ ] Añadir el método de set_autorization_token al README principal
* [ ] Permitir setear el método set_autorization_token desde un config file. (revisar que no haya más métodos de set que se puedan configurar mediante fichero y ver que todo siga funcionando).
* [ ] El método api_get_request si sale un código de error no puede hacer el json.loads y peta toda la ejecución

**Comment by SunD1995** [comment]
Incluido en la versión 2.2.4
